stages:
  - build
  - test
  - deploy

# --------------------------
# Global Variables
# --------------------------
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VENV_PATH: "$CI_PROJECT_DIR/djangoenv"
  DJANGO_ENV: "ci"
  DB_NAME: "$DB_NAME"
  DB_USER: "$DB_USER"
  DB_PASSWORD: "$DB_PASSWORD"
  DB_HOST: "mysql"

# ----------------------
# BUILD JOB
# ----------------------
build:
  stage: build
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev
    - python3 -m venv "$VENV_PATH"
    - source "$VENV_PATH/bin/activate"
    - pip install --upgrade pip
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - djangoenv/
    expire_in: 1 hour
  only:
    - main
    - QA
    - production

# ----------------------
# TEST JOB (fixed)
# ----------------------
test:
  stage: test
  image: python:3.11-slim
  services:
    - name: mysql:8.0                  # Changed to mysql:8.0 for version consistency
      alias: mysql
      variables:
        MYSQL_ROOT_PASSWORD: "Test11!!"
        MYSQL_DATABASE: "myproject"
        MYSQL_PASSWORD: "Test11!!"
        # Removed MYSQL_USER as root user is auto-created
  variables:
    DJANGO_ENV: "ci"
    DB_NAME: "myproject"
    DB_USER: "root"
    DB_PASSWORD: "Test11!!"
    DB_HOST: "mysql"
  before_script:
    # Installed default-mysql-client instead of mysql-client
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev default-mysql-client
    - source "$VENV_PATH/bin/activate"
    - pip install -r requirements.txt
  script:
    - echo "Sleeping 30s to ensure MySQL initialization..."
    - sleep 30
    - mysql --host=mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"
    - python manage.py test
  dependencies:
    - build
  only:
    - main
    - QA
    - production

# ----------------------
# DEPLOY JOB
# ----------------------
deploy:
  stage: deploy
  image: python:3.11-slim
  services:
    - name: mysql:8.0
      alias: mysql
      variables:
        MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
        MYSQL_DATABASE: "$MYSQL_DATABASE"
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev curl default-mysql-client  # Added default-mysql-client here
    - python3 -m venv "$VENV_PATH"
    - source "$VENV_PATH/bin/activate"
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Deploying Django application..."
    - python manage.py collectstatic --noinput
    - gunicorn myproject.wsgi:application --config gunicorn.conf.py --log-level debug &
    - sleep 10
    - curl --retry 5 --retry-delay 5 http://127.0.0.1:8080 || (echo "App failed to start"; exit 1)
  dependencies:
    - test
  environment:
    name: production
  only:
    - production
  when: manual