stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VENV_PATH: "$CI_PROJECT_DIR/djangoenv"

# ----------------------
# BUILD JOB
# ----------------------
build:
  stage: build
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev
    - python3 -m venv "$VENV_PATH"
    - source "$VENV_PATH/bin/activate"
    - pip install --upgrade pip
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - djangoenv/
    expire_in: 1 hour
  only:
    - main
    - QA
    - production

# ----------------------
# TEST JOB
# ----------------------
test:
  stage: test
  image: python:3.11-slim
  services:
    - name: mysql:8.0
      alias: mysql  # If you want a custom alias, but "mysql" is fine
  variables:
    # Pull all secrets from GitLab variables instead of hardcoding:
    DJANGO_ENV: "ci"
    MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    DB_NAME: "$DB_NAME"
    DB_USER: "$DB_USER"
    DB_PASSWORD: "$DB_PASSWORD"
    DB_HOST: "$DB_HOST"
    DB_PORT: "$DB_PORT"
  before_script:
    - apt-get update && apt-get install -y gcc libmariadb-dev pkg-config
    - source "$VENV_PATH/bin/activate"
  script:
    - echo "Sleeping 10s to let MySQL initialize..."
    - sleep 10
    - python manage.py test
  dependencies:
    - build
  only:
    - main
    - QA
    - production

# ----------------------
# DEPLOY JOB
# ----------------------
deploy:
  stage: deploy
  image: python:3.11-slim
  services:
    - name: mysql:latest
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    MYSQL_DATABASE: "$DB_NAME"
    DB_NAME: "$DB_NAME"
    DB_USER: "$DB_USER"
    DB_PASSWORD: "$DB_PASSWORD"
    DB_HOST: "$DB_HOST"
    DB_PORT: "$DB_PORT"
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev curl
    - python3 -m venv "$VENV_PATH"
    - source "$VENV_PATH/bin/activate"
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Deploying Django application..."
    - python manage.py collectstatic --noinput
    - gunicorn myproject.wsgi:application --config gunicorn.conf.py --log-level debug &
    - sleep 10
    - curl --retry 5 --retry-delay 5 http://127.0.0.1:8080 || (echo "App failed to start"; exit 1)
  dependencies:
    - test
  environment:
    name: production
  only:
    - production
  when: manual