stages:
  - build
  - test
  - deploy

# --------------------------
# Global Variables (Optional)
# --------------------------
# These refer to variables you'll define in GitLab -> Settings -> CI/CD -> Variables
# Example variable names: MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, DB_NAME, DB_USER, DB_PASSWORD, etc.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VENV_PATH: "$CI_PROJECT_DIR/djangoenv"
  DJANGO_ENV: "ci"             # for your test config
  DB_NAME: "$DB_NAME"          # read from GitLab CI variables
  DB_USER: "$DB_USER"          # read from GitLab CI variables
  DB_PASSWORD: "$DB_PASSWORD"  # read from GitLab CI variables
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"

# ----------------------
# BUILD JOB
# ----------------------
build:
  stage: build
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev
    - python3 -m venv "$VENV_PATH"
    - source "$VENV_PATH/bin/activate"
    - pip install --upgrade pip
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - djangoenv/
    expire_in: 1 hour
  only:
    - main
    - QA
    - production

# ----------------------
# TEST JOB
# ----------------------
test:
  stage: test
  image: python:3.11-slim
  services:
    - name: mysql:latest
      alias: mysql
  variables:
    MYSQL_DATABASE: "myproject"
    MYSQL_USER: "myuser"
    MYSQL_PASSWORD: "Test11!!"
    MYSQL_ROOT_PASSWORD: "Test11!!"
    DB_NAME: "myproject"
    DB_USER: "root"  # Use root ONLY FOR TESTS
    DB_PASSWORD: "Test11!!"
    DB_HOST: "mysql"
  before_script: 
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev
    - source "$VENV_PATH/bin/activate"
    - pip install -r requirements.txt
  script:
    - echo "Sleeping 20s to let MySQL initialize..."
    - sleep 20
    - python manage.py test
  dependencies:
    - build
  only:
    - main
    - QA
    - production

# ----------------------
# DEPLOY JOB
# ----------------------
deploy:
  stage: deploy
  image: python:3.11-slim
  services:
    - name: mysql:8.0
      alias: mysql
      variables:
        MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
        MYSQL_DATABASE: "$MYSQL_DATABASE"
        # same idea if you need separate user
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config libmariadb-dev curl
    - python3 -m venv "$VENV_PATH"
    - source "$VENV_PATH/bin/activate"
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Deploying Django application..."
    - python manage.py collectstatic --noinput
    - gunicorn myproject.wsgi:application --config gunicorn.conf.py --log-level debug &
    - sleep 10
    - curl --retry 5 --retry-delay 5 http://127.0.0.1:8080 || (echo "App failed to start"; exit 1)
  dependencies:
    - test
  environment:
    name: production
  only:
    - production
  when: manual