stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VENV_PATH: "$CI_PROJECT_DIR/djangoenv"

# --- Build job ---
build:
  stage: build
  image: python:3.11-slim
  before_script:
    - python3 -V  # Ensure Python is available
    - pip install --upgrade pip
  script:
    - rm -rf $VENV_PATH  # Ensure no conflicting venv exists
    - python3 -m venv $VENV_PATH  # Create virtual env
    - ls -al $VENV_PATH  # Debug: List venv contents
    - source $VENV_PATH/bin/activate
    - pip install -r requirements.txt
  cache:
    key: venv-cache
    paths:
      - .cache/pip
      - djangoenv/
  artifacts:
    paths:
      - djangoenv/
    expire_in: 1 hour
  only:
    - main
    - develop

# --- Test job ---
test:
  stage: test
  image: python:3.11-slim
  before_script:
    - ls -al $VENV_PATH  # Debug: List venv contents
    - source $VENV_PATH/bin/activate  # Activate virtual environment
  script:
    - python manage.py test || echo "No tests found, skipping."
  dependencies:
    - build
  only:
    - main
    - develop

# --- Deploy job (manual trigger) ---
deploy:
  stage: deploy
  image: python:3.11-slim
  before_script:
    - ls -al $VENV_PATH  # Debug: Ensure venv exists
    - source $VENV_PATH/bin/activate  # Activate virtual environment
  script:
    - echo "Deploying Django application..."
    - pip install gunicorn
    - python manage.py collectstatic --noinput
    - gunicorn myproject.wsgi:application --config gunicorn.conf.py
  dependencies:
    - test
  environment:
    name: production
  only:
    - main
  when: manual