# Generated by Django 5.0.6 on 2024-10-22 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_investmentcomparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCashFlowInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenor', models.CharField(max_length=255)),
                ('type_invest', models.CharField(max_length=255)),
                ('cash_flows', models.JSONField()),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IRR', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('NPV', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'custom_cash_flow_investments',
            },
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_52_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_52_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_data',
            },
        ),
        migrations.DeleteModel(
            name='InvestmentComparison',
        ),
        migrations.RenameField(
            model_name='investingrecord',
            old_name='rate',
            new_name='discount_rate',
        ),
        migrations.AddField(
            model_name='investingrecord',
            name='yearly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investingrecord',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investingrecord',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investingrecord',
            name='tenor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investingrecord',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investingrecord',
            name='type_invest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customcashflowinvestment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
